package bashtravel;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form Tabout
     */
    public About() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        deskripsiBash = new javax.swing.JLabel();
        Atas = new javax.swing.JPanel();
        atur = new javax.swing.JLabel();
        semarang = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bawah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nohp = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        contactInfo = new javax.swing.JLabel();
        Bulet = new RoundedPanel(300,Color.white);
        logo = new javax.swing.JLabel();
        BashTravel = new javax.swing.JLabel();
        tour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tentang Kami");

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));
        jPanel1.setLayout(null);

        back.setBackground(new java.awt.Color(255, 255, 51));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(80, 480, 70, 25);

        deskripsiBash.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        deskripsiBash.setForeground(new java.awt.Color(255, 255, 255));
        deskripsiBash.setText("<html>\n\tBashTravel adalah<br>\n                       perusahaan yang<br>\n                     menyediakan akses bagi <br>\n                        masyarakat untuk<br>\n                    menemukan dan memesan<br>\n                         berbagai layanan<br>\n                               transportasi<br>\n");
        deskripsiBash.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(deskripsiBash);
        deskripsiBash.setBounds(50, 160, 230, 160);

        Atas.setBackground(new java.awt.Color(255, 255, 0));
        Atas.setLayout(null);

        atur.setFont(new java.awt.Font("Tw Cen MT", 0, 13)); // NOI18N
        atur.setText("Atur perjalanan ke ");
        Atas.add(atur);
        atur.setBounds(40, 5, 110, 20);

        semarang.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        semarang.setForeground(new java.awt.Color(44, 62, 80));
        semarang.setText("SEMARANG");
        Atas.add(semarang);
        semarang.setBounds(40, 20, 105, 30);

        jLabel3.setText("Bersama kami!");
        Atas.add(jLabel3);
        jLabel3.setBounds(40, 47, 90, 16);

        jPanel1.add(Atas);
        Atas.setBounds(0, 50, 600, 70);

        Bawah.setBackground(new java.awt.Color(236, 240, 241));
        Bawah.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/smg.jpg"))); // NOI18N
        Bawah.add(jLabel2);
        jLabel2.setBounds(10, 10, 331, 160);

        jPanel1.add(Bawah);
        Bawah.setBounds(240, 360, 360, 180);

        nohp.setFont(new java.awt.Font("Tw Cen MT", 0, 13)); // NOI18N
        nohp.setForeground(new java.awt.Color(255, 255, 255));
        nohp.setText("0812345678910");
        jPanel1.add(nohp);
        nohp.setBounds(70, 420, 110, 18);

        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("BashTravel@gmail.com");
        jPanel1.add(Email);
        Email.setBounds(50, 400, 140, 16);

        contactInfo.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        contactInfo.setForeground(new java.awt.Color(255, 255, 255));
        contactInfo.setText("CONTACT INFO");
        jPanel1.add(contactInfo);
        contactInfo.setBounds(50, 360, 140, 30);

        Bulet.setBackground(new java.awt.Color(52, 152, 219));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ss logo.png"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(50, 50));
        logo.setMinimumSize(new java.awt.Dimension(50, 50));
        logo.setPreferredSize(new java.awt.Dimension(50, 50));

        BashTravel.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        BashTravel.setText("BASH TRAVEL");

        tour.setFont(new java.awt.Font("Tw Cen MT", 2, 10)); // NOI18N
        tour.setText("TOUR & TRAVEL");

        javax.swing.GroupLayout BuletLayout = new javax.swing.GroupLayout(Bulet);
        Bulet.setLayout(BuletLayout);
        BuletLayout.setHorizontalGroup(
            BuletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuletLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(BuletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuletLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BashTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BuletLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tour, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        BuletLayout.setVerticalGroup(
            BuletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuletLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BashTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tour, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(Bulet);
        Bulet.setBounds(340, 170, 170, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Beranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Atas;
    private javax.swing.JLabel BashTravel;
    private javax.swing.JPanel Bawah;
    private javax.swing.JPanel Bulet;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel atur;
    private javax.swing.JButton back;
    private javax.swing.JLabel contactInfo;
    private javax.swing.JLabel deskripsiBash;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nohp;
    private javax.swing.JLabel semarang;
    private javax.swing.JLabel tour;
    // End of variables declaration//GEN-END:variables


    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
